---
title: "GroupA_HM2"
author: "Munini, Tallone, El gataa, E.Ruoppolo"
output: 
  pdf_document:
    toc: true
    toc_depth: 3
date: "2022-10-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## FSDS - Chapter 3

### Ex 3.12

*Simulate random sampling from a normal population distribution with several n values to illustrate the law of large numbers*

**Solution**

Add comments to the solution.

### Ex 3.18

*Sunshine City, which attracts primarily retired people, has 90,000 residents with a mean age of 72 years and a standard deviation of 12 years. The age distribution is skewed to the left. A random sample of 100 residents of Sunshine City has* $\bar{y}=70$ *and* $s=11$.

-   *Describe the center and spread of the (i) population distribution, (ii) sample data distribution. What shape does the sample data distribution probably have? Why?*
-   *Find the center and spread of the sampling distribution of* $\overline{\text{Y}}$ *for* $n=100$. *What shape does it have and what does it describe?*
-   *Explain why it would not be unusual to sample a person of age 60 in Sunshine City, but it would be highly unusual for the sample mean to be 60, for a random sample of 100 residents.*
-   *Describe the sampling distribution of* $\overline{\text{Y}}$ *: (i) for a random sample of size* $n=1$; *(ii) if you sample all 90,000 residents.*

**Solution**

Add comments to the solution.

### Ex 3.28

*A survey is planned to estimate the population proportion* $\pi$ *supporting more government action to address global warming. For a simple random sample, if* $\pi$ *may be near 0.50, how large should n be so that the standard error of the sample proportion is 0.04?*

**Solution**

Add comments to the solution.

## FSDS - Chapter 4

### Ex 4.2

*Here the text of the first exercise.*

**Solution**

Add comments to the solution.

### Ex 4.4

*For the* ``Students`` *data file (Exercise 1.2 in Chapter 1) and corresponding population, find the ML estimate of the population proportion believing in life after death. Construct a Wald 95% confidence interval, using its formula (4.8). Interpret.*

**Solution**

Add comments to the solution.

### Ex 4.38

*For independent observations* $y_1, \dots, y_n$ *having the geometric distribution (2.1):*

-   *Find a sufficient statistic for* $\pi$;
-   *Derive the ML estimator for* $\pi$.

**Solution**

Add comments to the solution.

### Ex 4.44

*Refer to the previous two exercises. Consider the selling prices (in thousands of dollars) in the* ``Houses`` *data file mentioned in Exercise 4.31.*

-   *Fit the normal distribution to the data by finding the ML estimates of* $\mu$ *and* $\sigma$ *for that distribution.*
-   *Fit the log-normal distribution to the data by finding the ML estimates of its parameters.*
-   *Find and compare the ML estimates of the mean and standard deviation of selling price for the two distributions.*
-   *Superimpose the fitted normal and log-normal distributions on a histogram of the data. Which distribution seems to be more appropriate for summarizing the selling prices?*

**Solution**

Add comments to the solution.

### Ex 4.48

*For a simple random sample of * ${n}$ *subjects, explain why it is about 95% likely that the sample proportion has error no more than* $1/\sqrt{n}$ *in estimating the population proportion. (Hint: To show this “* $1/\sqrt{n}$ *rule”, find two standard errors when * $\pi=0.50$ *, and explain how this compares to two standard errors at other values of * $\pi$ *.) Using this result, show that * $n=1/M^2$ *is a safe sample size for estimating a proportion to within * $M$ *with 95% confidence.*

**Solution**

Add comments to the solution.

## FSDS - Chapter 5

### Ex 5.2

*When a government does not have enough money to pay for the services that it provides, it can raise taxes or it can reduce services. When the Florida Poll asked a random sample of 1200 Floridians which they preferred, 52% (624 of the 1200) chose raise taxes and 48% chose reduce services. Let * $\pi$ *denote the population proportion of Floridians who would choose raising taxes.Analyze whether this is a minority of the population * $(\pi<0.50)$ *or a majority * $(\pi>0.50)$ *by testing * $H_0\,:\,\pi=0.50$ *against* $H_\alpha\,:\,\pi\neq0.50$ *. Interpret the P-value. Is it appropriate to "accept"* $H_0$ *? Why or why not?*

**Solution**

Add comments to the solution.

### Ex 5.12

*The example in Section 3.1.4 described an experiment to estimate the mean sales with a proposed menu for a new restaurant. In a revised experiment to compare two menus, on Tuesday of the opening week the owner gives customers menu A and on Wednesday she gives them menu B. The bills average $22.30 for the 43 customers on Tuesday (s = 6.88) and $25.91 for the 50 customers on Wednesday (s = 8.01). Under the strong assumption that her customers each night are comparable to a random sample from the conceptual population of potential customers, show how to compare the mean sales for the two menus based on (a) the P-value of a significance test, (b) a 95% confidence interval. Which is more informative, and why? (When used in an experiment to compare two treatments to determine which works better, a two-sample test is often called an A/B test.).*

**Solution**

Add comments to the solution.

### Ex 5.68

*Explain why the confidence interval based on the Wald test of * $H_0\,:\,\theta=\theta_0$ *is symmetric around * $\hat\theta$ *(i.e., having center exactly equal to* $\hat\theta$ *. This is not true for the confidence intervals based on the likelihood-ratio and score tests.) Explain why such symmetry can be problematic when * $\theta$ *and * $\hat\theta$ *are near a boundary, using the example of a population proportion that is very close to 0 or 1 and a sample proportion that may well equal 0 or 1.*

**Solution**

Add comments to the solution.
